@baseUrl = http://localhost:3000

### Obtener todas las recompensas
GET {{baseUrl}}/recompensas

### Canjear una recompensa
POST {{baseUrl}}/recompensas/1/canjear
Content-Type: application/json

{
  "id_usuario": 1
}