###
# ==============================================================================
# ROLES
# ==============================================================================

### Obtener todos los roles
GET http://localhost:3000/admin/roles

### Crear un nuevo rol
POST http://localhost:3000/admin/roles
Content-Type: application/json

{
  "nombre": "Supervisor",
  "descripcion": "Supervisa el contenido y los usuarios.",
  "icono_url": "/icons/supervisor.png"
}

### Obtener un rol por ID
# @name getRoleById
GET http://localhost:3000/admin/roles/4

### Eliminar un rol
DELETE http://localhost:3000/admin/roles/4

### Asignar permisos a un rol
# Asigna los permisos con ID 1, 2 y 3 al rol con ID 4
POST http://localhost:3000/admin/roles/4/permisos
Content-Type: application/json

{
  "permissionIds": [1, 2, 3]
}

# ==============================================================================
# PERMISOS
# ==============================================================================

### Obtener todos los permisos
GET http://localhost:3000/admin/permisos