@baseUrl = http://localhost:5000/admin

# ==============================================================================
# ROLES
# ==============================================================================

### Obtener todos los roles
GET {{baseUrl}}/roles

### Crear un nuevo rol
POST {{baseUrl}}/roles
Content-Type: application/json

{
  "nombre": "Supervisor_Test",
  "descripcion": "Supervisa el contenido y los usuarios de prueba.",
  "icono_url": "/icons/supervisor_test.png"
}

### Obtener un rol por ID
# @name getRoleById
GET {{baseUrl}}/roles/4

### Eliminar un rol
# Reemplaza el 4 con el ID del rol que quieres eliminar
DELETE {{baseUrl}}/roles/4

### Asignar permisos a un rol
# Asigna los permisos con ID 1, 2 y 3 al rol con ID 4
POST {{baseUrl}}/roles/4/permisos
Content-Type: application/json

{
  "permissionIds": [1, 2, 3]
}
# ==============================================================================
# PERMISOS
# ==============================================================================

### Obtener todos los permisos
GET {{baseUrl}}/permisos