@baseUrl = http://localhost:5000/entregas

### 1. Crear una nueva entrega (Tarea)
# @name createTareaEntrega
POST {{baseUrl}}
Content-Type: application/json

{
  "id_usuario": 1,
  "id_tarea": 5,
  "url_archivo": "https://example.com/path/to/mi_tarea.pdf"
}

### 2. Crear una nueva entrega (Evaluación)
# @name createEvaluacionEntrega
POST {{baseUrl}}
Content-Type: application/json

{
  "id_usuario": 1,
  "id_evaluacion": 3
}

### 3. Obtener el progreso de una lección
# @name getLeccionProgreso
# Reemplaza :id_usuario y :id_leccion con los IDs correspondientes
GET {{baseUrl}}/progreso/1/12

### Calificar una entrega (Tarea o Evaluación)
# Reemplaza el :id con el ID de la entrega_actividad que quieres calificar.
# El ID de la entrega se obtiene cuando un estudiante realiza una entrega.
#
# El cuerpo de la petición debe contener la calificación.
# La calificación debe ser un número entre 0 y 100.
#
# Al calificar, el estado de la entrega cambiará a 'Calificado' y si la nota
# es de aprobación, se disparará el trigger para asignar puntos al usuario.
PATCH {{baseUrl}}/4/calificar
Content-Type: application/json

{
  "calificacion": 85
}

### 5. Listar todas las entregas de un curso
# Reemplaza :id_curso con el ID del curso que quieres consultar.
GET {{baseUrl}}/curso/4

### 6. Obtener una entrega específica por su ID
# Reemplaza :id con el ID de la entrega que quieres consultar.
GET {{baseUrl}}/4

### 7. Listar todas las entregas de un usuario en un curso específico
# Reemplaza :id_usuario y :id_curso con los IDs correspondientes.
GET {{baseUrl}}/usuario/2/curso/4

---
### 8. Obtener reporte de notas de evaluaciones
# @name getReporteNotasEvaluaciones
GET {{baseUrl}}/reportes/notas-evaluaciones