@baseUrl = http://localhost:3000

### Obtener todas las recompensas disponibles
GET {{baseUrl}}/recompensas

### Canjear una recompensa
# @name canjearRecompensa
POST {{baseUrl}}/recompensas/1/canjear
Content-Type: application/json

{
  "id_usuario": 1
}