@baseUrl = http://localhost:5000

### Obtener todas las recompensas disponibles
GET {{baseUrl}}/recompensas

### Canjear una recompensa
# @name canjearRecompensa
POST {{baseUrl}}/recompensas/4/canjear
Content-Type: application/json

{
  "id_usuario": 5
}